- project:
    name: openstack/swift3
    check:
      jobs:
        - swift3-tox-keystone
        - swift3-tox-s3acl
        - swift3-tox-tempauth
        - swift3-tox-s3tests_keystone:
            voting: false
        - swift3-tox-s3tests_tempauth:
            voting: false
    gate:
      jobs:
        - swift3-tox-keystone
        - swift3-tox-s3acl
        - swift3-tox-tempauth

- job:
    name: swift3-tox-keystone
    parent: openstack-tox-py27
    description: |
      Run tests using ``keystone`` environment.
    vars:
      tox_envlist: keystone

- job:
    name: swift3-tox-s3acl
    parent: openstack-tox-py27
    description: |
      Run tests using ``s3acl`` environment.
    vars:
      tox_envlist: s3acl

- job:
    name: swift3-tox-tempauth
    parent: openstack-tox-py27
    description: |
      Run tests using ``tempauth`` environment.
    vars:
      tox_envlist: tempauth

- job:
    name: swift3-tox-s3tests_keystone
    parent: openstack-tox-py27
    description: |
      Run tests using ``s3tests_keystone`` environment.
    vars:
      tox_envlist: s3tests_keystone

- job:
    name: swift3-tox-s3tests_tempauth
    parent: openstack-tox-py27
    description: |
      Run tests using ``s3tests_tempauth`` environment.
    vars:
      tox_envlist: s3tests_tempauth
