#!/bin/bash

# HEAD Object

. ./common

S3USER=tester

_s3_put /bucket

echo data > $tmp.data
MD5=$(_md5 $tmp.data) CONTENT_TYPE='application/octet-stream' \
    _s3_put /bucket/a -T $tmp.data \
    -H 'Content-Disposition: attachment; filename="a.txt.gz"' \
    -H 'Content-Encoding: gzip' \
    -H "Content-Length: $(_file_size $tmp.data)" \
    -H 'x-amz-storage-class: STANDARD' \
    -H "x-amz-meta-hoge: hoge" -D - | _filter_curl

_s3_head /bucket/a | _filter_curl
