#!/bin/bash

# List Multipart Uploads

. ./common


S3USER=tester

_s3_put /bucket

upload_id=$(_s3_post /bucket/object?uploads | _xpath '/InitiateMultipartUploadResult/UploadId/text()')
upload_id2=$(_s3_post /bucket/object?uploads | _xpath '/InitiateMultipartUploadResult/UploadId/text()')
upload_id3=$(_s3_post /bucket/object2?uploads | _xpath '/InitiateMultipartUploadResult/UploadId/text()')

_s3_get /bucket?uploads -D - | _filter_curl xml

